name: Build FreeRTOS-Emulator

on:
  pull_request:
    branches:
      - master
      - clean
      - udo_demo
      - pong
      - ci
  push:
    branches:
      - master
      - clean
      - udo_demo
      - pong
      - ci

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    name: Standard Build
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2 Dependencies
        run: sudo apt-get install -y libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-gfx-dev libsdl2-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure CMake
        run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
      - name: Build with CMake
        run: cd build && make
  doxygen:
    name: Doxygen Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Generate Doxygen Documentation
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: docs
      - name: Print warnings
        run: |
          if [[ -s "doxygen_warnings.txt" ]]; then
            echo "You must fix doxygen before submitting a pull request"
            echo "Build doxygen: 'cmake -DDOCS=ON .. & make docs'"
            echo ""
            cat doxygen_warnings.txt
            exit -1
          fi
      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/docs/html
  git_check:
    name: Run Git Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Check and Print Warning
        run: |
          if [[ -n $(git diff --check HEAD^) ]]; then
            echo "You must remove whitespace before submitting a pull request"
            echo ""
            git diff --check HEAD^
            exit -1
          fi
  astyle_format:
    name: Run AStyle Format
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2 Dependencies
        run: sudo apt-get install -y astyle libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-gfx-dev libsdl2-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure CMake
        run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_ASTYLE=ON ..
      - name: Build with CMake
        run: cd build && make
      - name: Run Checks
        run: cd build && make format
      - name: Print Warnings
        run: |
          if [[ -n $(git diff) ]]; then
            echo "You must run make format before submitting a pull request"
            echo ""
            git diff
            exit -1
          fi
  cppcheck:
    name: Run CPPCheck
    runs-on: ubuntu-latest
    steps:
      - name: Install SDL2 Dependencies
        run: sudo apt-get install -y cppcheck libsdl2-ttf-dev libsdl2-mixer-dev libsdl2-image-dev libsdl2-gfx-dev libsdl2-dev
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure CMake
        run: mkdir -p build && cd build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_CPPCHECK=ON ..
      - name: Build with CMake
        run: cd build && make
      - name: Run Checks
        run: cd build && make check
